# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SocialIntegration' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'FBSDKLoginKit', '~> 4.29'
  pod 'FBSDKCoreKit', '~> 4.29'
  pod 'FBSDKShareKit', '~> 4.29'
  pod 'GoogleSignIn', '~> 4.1'
end
